### ISSUE TITLE
This is not an issue. But I don't know how to get to the dashboard.

### ISSUE THREAD

**Issue by ghost** [scholzj/aws-kubernetes#4]
I don't know how to get to the dashboard. Which url

**Comment by ghost** [comment]
I am not able to install Kubernetes on the master or the node. The User data is not getting passed or some issue. Don't know how to troubleshoot.

**Comment by scholzj** [comment]
The Dashboard is not exposed directly to the internet. I usually access it using the kubectl tool:
1. Start the `kubectl proxy`
2. Open url http://127.0.0.0.1:8001/ui in your browser

**Comment by scholzj** [comment]
If the master / node fails to start (or connect to the cluster) the best way for debugging is to log into the node using SSH and check the content of a file `/var/log/cloud-init-output.log`. This file contains the log from the User data script and should be helpfull. It sometimes happens that the cloud init script fails because the RPM repositories were down or something like that. such things should be visible in this log.

I would not expect a problem with the User data section content it self - but you should be able to see what is in the User data section either through the AWS Console or if you SSH into the host it should be in the instance metadata `curl http://169.254.169.254/latest/user-data`.

**Comment by scholzj** [comment]
I will close this as there was no reply for few weeks. Feel free to reopen / raise a new issue if you have some more questions.
